-- 실행용 DDL 은 레포에서 제거됨. 백업 후 아래를 DB 클라이언트에서 수동 실행(이미 컬럼/키 있으면 해당 줄 스킵).
--
-- ALTER TABLE member
--     ADD COLUMN profile_image_file_seq BIGINT NULL COMMENT 'attach_file.file_seq' AFTER profile_image_url;
--
-- ALTER TABLE member
--     ADD CONSTRAINT fk_member_profile_image_file
--         FOREIGN KEY (profile_image_file_seq) REFERENCES attach_file (file_seq) ON DELETE SET NULL;
