-- 실행용 DDL 은 레포에서 제거됨. 백업 후 수동 실행(컬럼 이미 있으면 오류 → 해당 문장만 생략).
--
-- ALTER TABLE calendar_schedule
--     ADD COLUMN category_code VARCHAR(100) NULL COMMENT '공통코드 그룹 A0003 code_value' AFTER title;
--
-- ALTER TABLE calendar_schedule
--     ADD COLUMN start_time TIME NULL COMMENT '시작 시각(선택, 일정만)' AFTER end_date;
--
-- ALTER TABLE calendar_schedule
--     ADD COLUMN end_time TIME NULL COMMENT '종료 시각(선택, 일정만)' AFTER start_time;
