-- uk_ebb_event_member 제거는 수동 실행. (PREPARE 블록은 레포에서 제거됨)
--
-- SET @db := DATABASE();
-- SET @sql := (
--     SELECT IF(
--         (SELECT COUNT(*) FROM information_schema.STATISTICS
--          WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'event_battle_bet' AND INDEX_NAME = 'uk_ebb_event_member') > 0,
--         'ALTER TABLE event_battle_bet DROP INDEX uk_ebb_event_member',
--         'SELECT 1'
--     )
-- );
-- PREPARE _stmt FROM @sql;
-- EXECUTE _stmt;
-- DEALLOCATE PREPARE _stmt;
